List<Map<String, dynamic>> countryCode = [
  {
    "AF": "Africa",
    "AL": "Europe",
    "DZ": "Africa",
    "AS": "Oceania",
    "AD": "Europe",
    "AO": "Africa",
    "AI": "North America",
    "AQ": "Antarctica",
    "AG": "North America",
    "AR": "South America",
    "AM": "Asia",
    "AW": "North America",
    "AU": "Australia",
    "AT": "Europe",
    "AZ": "Asia",
    "BS": "North America",
    "BH": "Asia",
    "BD": "Asia",
    "BB": "North America",
    "BY": "Europe",
    "BE": "Europe",
    "BZ": "North America",
    "BJ": "Africa",
    "BM": "North America",
    "BT": "Asia",
    "BO": "South America",
    "BA": "Europe",
    "BW": "Africa",
    "BR": "South America",
    "BN": "Asia",
    "BG": "Europe",
    "BF": "Africa",
    "BI": "Africa",
    "CV": "Africa",
    "KH": "Asia",
    "CM": "Africa",
    "CA": "North America",
    "KY": "North America",
    "CF": "Africa",
    "TD": "Africa",
    "CL": "South America",
    "CN": "Asia",
    "CO": "South America",
    "KM": "Africa",
    "CG": "Africa",
    "CD": "Africa",
    "CR": "North America",
    "HR": "Europe",
    "CU": "North America",
    "CY": "Europe",
    "CZ": "Europe",
    "DK": "Europe",
    "DJ": "Africa",
    "DM": "North America",
    "DO": "North America",
    "EC": "South America",
    "EG": "Africa",
    "SV": "North America",
    "GQ": "Africa",
    "ER": "Africa",
    "EE": "Europe",
    "SZ": "Africa",
    "ET": "Africa",
    "FJ": "Oceania",
    "FI": "Europe",
    "FR": "Europe",
    "GA": "Africa",
    "GM": "Africa",
    "GE": "Asia",
    "DE": "Europe",
    "GH": "Africa",
    "GR": "Europe",
    "GD": "North America",
    "GT": "North America",
    "GN": "Africa",
    "GW": "Africa",
    "GY": "South America",
    "HT": "North America",
    "HN": "North America",
    "HU": "Europe",
    "IS": "Europe",
    "IN": "Asia",
    "ID": "Asia",
    "IR": "Asia",
    "IQ": "Asia",
    "IE": "Europe",
    "IL": "Asia",
    "IT": "Europe",
    "JM": "North America",
    "JP": "Asia",
    "JE": "Europe",
    "JO": "Asia",
    "KZ": "Asia",
    "KE": "Africa",
    "KI": "Oceania",
    "KP": "Asia",
    "KR": "Asia",
    "KW": "Asia",
    "KG": "Asia",
    "LA": "Asia",
    "LV": "Europe",
    "LB": "Asia",
    "LS": "Africa",
    "LR": "Africa",
    "LY": "Africa",
    "LI": "Europe",
    "LT": "Europe",
    "LU": "Europe",
    "MO": "Asia",
    "MG": "Africa",
    "MW": "Africa",
    "MY": "Asia",
    "MV": "Asia",
    "ML": "Africa",
    "MT": "Europe",
    "MH": "Oceania",
    "MQ": "North America",
    "MR": "Africa",
    "MU": "Africa",
    "MX": "North America",
    "FM": "Oceania",
    "MD": "Europe",
    "MC": "Europe",
    "MN": "Asia",
    "ME": "Europe",
    "MA": "Africa",
    "MZ": "Africa",
    "MM": "Asia",
    "NA": "Africa",
    "NR": "Oceania",
    "NP": "Asia",
    "NL": "Europe",
    "NZ": "Oceania",
    "NI": "North America",
    "NE": "Africa",
    "NG": "Africa",
    "NU": "Oceania",
    "NF": "Oceania",
    "NO": "Europe",
    "OM": "Asia",
    "PK": "Asia",
    "PW": "Oceania",
    "PA": "North America",
    "PG": "Oceania",
    "PY": "South America",
    "PE": "South America",
    "PH": "Asia",
    "PL": "Europe",
    "PT": "Europe",
    "QA": "Asia",
    "RE": "Africa",
    "RO": "Europe",
    "RU": "Europe",
    "RW": "Africa",
    "BL": "North America",
    "SH": "Africa",
    "KN": "North America",
    "LC": "North America",
    "MF": "North America",
    "PM": "North America",
    "VC": "North America",
    "WS": "Oceania",
    "SM": "Europe",
    "ST": "Africa",
    "SA": "Asia",
    "SN": "Africa",
    "RS": "Europe",
    "SC": "Africa",
    "SL": "Africa",
    "SG": "Asia",
    "SX": "North America",
    "SK": "Europe",
    "SI": "Europe",
    "SB": "Oceania",
    "SO": "Africa",
    "ZA": "Africa",
    "SS": "Africa",
    "ES": "Europe",
    "LK": "Asia",
    "SD": "Africa",
    "SR": "South America",
    "SE": "Europe",
    "CH": "Europe",
    "SY": "Asia",
    "TJ": "Asia",
    "TZ": "Africa",
    "TH": "Asia",
    "TG": "Africa",
    "TK": "Oceania",
    "TO": "Oceania",
    "TT": "North America",
    "TN": "Africa",
    "TR": "Asia",
    "TM": "Asia",
    "TV": "Oceania",
    "UG": "Africa",
    "UA": "Europe",
    "AE": "Asia",
    "GB": "Europe",
    "US": "North America",
    "UY": "South America",
    "UZ": "Asia",
    "VU": "Oceania",
    "VE": "South America",
    "VN": "Asia",
    "WF": "Oceania",
    "EH": "Africa",
    "YE": "Asia",
    "ZM": "Africa",
    "ZW": "Africa",
    "HK": "Asia",
  }
];
